In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
df.head(1001)

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
0             1    15634602    Hargrave          619    France  Female   42   
1             2    15647311        Hill          608     Spain  Female   41   
2             3    15619304        Onio          502    France  Female   42   
3             4    15701354        Boni          699    France  Female   39   
4             5    15737888    Mitchell          850     Spain  Female   43   
...         ...         ...         ...          ...       ...     ...  ...   
996         997    15645621      Hunter          811     Spain    Male   44   
997         998    15608114     Manfrin          587     Spain    Male   62   
998         999    15659557  Artamonova          811   Germany  Female   28   
999        1000    15787772      Hansen          759    France  Female   38   
1000       1001    15691111         Pai          648   Germany  Female   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
996        3       0.00              2          0               1   
997        7  121286.27              1          0               1   
998        4  167738.82              2          1               1   
999        1  104091.29              1          0               0   
1000       8  121980.56              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
996          78439.73       0  
997           6776.92       0  
998           9903.42       0  
999          91561.91       0  
1000          4027.02       0  

[1001 rows x 14 columns]

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder ()

In [17]:
df['Gender'] = le.fit_transform(df['Gender'])

In [20]:
df['Geography'] = le.fit_transform(df['Geography'])

In [21]:
df['Surname'] = le.fit_transform(df['Surname'])

In [22]:
df.head(1001)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          2       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          2       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
996         997    15645621     1252          811          2       1   44   
997         998    15608114     1667          587          2       1   62   
998         999    15659557      109          811          1       0   28   
999        1000    15787772     1106          759          0       0   38   
1000       1001    15691111     2098          648          1       0   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
996        3       0.00              2          0               1   
997        7  121286.27              1          0               1   
998        4  167738.82              2          1               1   
999        1  104091.29              1          0               0   
1000       8  121980.56              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
996          78439.73       0  
997           6776.92       0  
998           9903.42       0  
999          91561.91       0  
1000          4027.02       0  

[1001 rows x 14 columns]

In [28]:
x = df.iloc[:,0:14].values

In [29]:
x

array([[1.0000000e+00, 1.5634602e+07, 1.1150000e+03, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [2.0000000e+00, 1.5647311e+07, 1.1770000e+03, ..., 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00],
       [3.0000000e+00, 1.5619304e+07, 2.0400000e+03, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [9.9980000e+03, 1.5584532e+07, 1.5700000e+03, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [9.9990000e+03, 1.5682355e+07, 2.3450000e+03, ..., 0.0000000e+00,
        9.2888520e+04, 1.0000000e+00],
       [1.0000000e+04, 1.5628319e+07, 2.7510000e+03, ..., 0.0000000e+00,
        3.8190780e+04, 0.0000000e+00]])

In [34]:
#split the data dependent and independent variable
y = df.iloc[:,9:].values
y = df.iloc[:,9:].values

In [35]:
y

array([[1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05,
        1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05,
        0.0000000e+00],
       [3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05,
        1.0000000e+00],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 4.2085580e+04,
        1.0000000e+00],
       [2.0000000e+00, 1.0000000e+00, 0.0000000e+00, 9.2888520e+04,
        1.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.8190780e+04,
        0.0000000e+00]])

In [36]:
#split into data into training and testing
from sklearn.model_selection import train_test_split 

In [37]:
xtrain,xtest,ytrain,ytest = train_test_split (x,y,test_size=0.3,random_state=0)

In [39]:
xtrain.shape,xtest.shape

((7000, 14), (3000, 14))

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [52]:
ypred = reg.predict(xtest)

In [72]:
df.head()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   
3          4    15701354      289          699          0       0   39   
4          5    15737888     1822          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [73]:
np.round(ypred).astype('int')

array([[    9395, 15615753,     2691, ...,        1,   192853,        0],
       [     899, 15654700,      846, ...,        0,   128702,        1],
       [    2399, 15633877,     1857, ...,        1,    75732,        0],
       ...,
       [    9308, 15680405,     2089, ...,        1,   167400,        0],
       [    8395, 15597983,      336, ...,        1,    70849,        0],
       [    5234, 15591286,     2453, ...,        1,    33759,        1]])

In [79]:
df.head(1001)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          2       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          2       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
996         997    15645621     1252          811          2       1   44   
997         998    15608114     1667          587          2       1   62   
998         999    15659557      109          811          1       0   28   
999        1000    15787772     1106          759          0       0   38   
1000       1001    15691111     2098          648          1       0   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
996        3       0.00              2          0               1   
997        7  121286.27              1          0               1   
998        4  167738.82              2          1               1   
999        1  104091.29              1          0               0   
1000       8  121980.56              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
996          78439.73       0  
997           6776.92       0  
998           9903.42       0  
999          91561.91       0  
1000          4027.02       0  

[1001 rows x 14 columns]

In [80]:
np.round(ypred).astype('int')

array([[    9395, 15615753,     2691, ...,        1,   192853,        0],
       [     899, 15654700,      846, ...,        0,   128702,        1],
       [    2399, 15633877,     1857, ...,        1,    75732,        0],
       ...,
       [    9308, 15680405,     2089, ...,        1,   167400,        0],
       [    8395, 15597983,      336, ...,        1,    70849,        0],
       [    5234, 15591286,     2453, ...,        1,    33759,        1]])